# Generated by Django 3.2.16 on 2023-03-07 19:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0004_coursefeedback"),
    ]

    operations = []
